Electros/Electros/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Common;
using Electros.Models;
using Electros.ProductOrderServ;

namespace Electros.Controllers
{
    public class ProductController : Controller
    {
        //
        // GET: /Product/
        List<Product> products = new List<Product>();
        public ActionResult ProductList()
        {
           // List<Category> events = new CatServ.CategoryServiceClient().getCategories().ToList();
            // List<TestModel> events = new TestModel().category.ToList();
           // return View("Index", events);
            products = new ProductServ.ProductServiceClient().GetAllProducts().ToList();
            return View("ProductList", products);
        }


        //public ActionResult PDF()
        //{
        //    products = new ProductServ.ProductServiceClient().GetAllProducts().ToList();
        //    return new RazorPDF.PdfResult(products, "PDF");

        //}

        public ActionResult Filter(string category, string name, string lowPrice, string highPrice)
        {
            decimal parsed ;
            try
            {
                //to check type of price
                //if ((category == null || category == "") && (name == null || name == "") && Decimal.TryParse(lowPrice, out parsed) && Decimal.TryParse(highPrice, out parsed)  )
               
                if (!Decimal.TryParse(lowPrice, out parsed) && !Decimal.TryParse(highPrice, out parsed)  )
                {
                    List<Product> pro = new ProductServ.ProductServiceClient().GetAllProducts().ToList();
                    TempData["Error"] = "Price needs to be of type decimal (2.00)";
                    return View("ProductList", pro);
                }
                //to check for nulls
                if ((category == null || category == "") && (name == null || name == "") && (lowPrice == null || lowPrice == "") && (highPrice == null || highPrice == ""))
                {
                    TempData["Null"] = "One of the values is required";
                   // return View("ProductList", products);
                }

                if ((category != null || category != "") && (name == null || name == "") && (lowPrice == null || lowPrice == "") && (highPrice == null || highPrice == ""))
                {
                    products = new ProductServ.ProductServiceClient().searchByCategory(category).ToList();
                }
                else if ((category == null || category == "") && (name != null || name != "") && (lowPrice == null || lowPrice == "") && (highPrice == null || highPrice == ""))
                {
                    products = new ProductServ.ProductServiceClient().searchByName(name).ToList();
                }
                else if ((category == null || category == "") && (name == null || name == "") && (lowPrice != null || lowPrice != "") && (highPrice != null || highPrice != ""))
                {
                    decimal lPrice = Convert.ToDecimal(lowPrice);
                    decimal hPrice = Convert.ToDecimal(highPrice);
                    products = new ProductServ.ProductServiceClient().searchByPriceRange(lPrice, hPrice).ToList();
                }
                return View("ProductList", products);
            }
            catch (Exception ex)
            {
                TempData["CatchError"] = "An error was encountered. Please try again later";
                return View("ProductList", products);
            }
        }

        public ActionResult SortByHighPrice()
        {
            products = new ProductServ.ProductServiceClient().sortByDescPrice().ToList();
            return View("ProductList", products);
        }

        public ActionResult SortByLowPrice()
        {
            products = new ProductServ.ProductServiceClient().sortByAscPrice().ToList();
            return View("ProductList", products);
        }

        public ActionResult SortByDate()
        {
            products = new ProductServ.ProductServiceClient().sortByDateListed().ToList();
            return View("ProductList", products);
        }
        //[Authorize(Roles = "Admin")]
       // [Authorize(Roles = "Admin, User")]
        public ActionResult Details(int id)
        {
             Product p = new ProductServ.ProductServiceClient().GetProductByID(id);
             IEnumerable<Comment> c = new ProductServ.ProductServiceClient().GetCommentByProductID(id);
             double avgRating = new ProductServ.ProductServiceClient().getAverageRating(id);
             ProductModel model = new ProductModel();
             model.myProduct = p;
             model.myComment = c.ToList();
             model.averageRating = avgRating;
            return View(model);
        }

        [Authorize(Roles = "Admin, User")]
        [HttpPost]
        public ActionResult AddToCart(ProductModel p)
        {
            try
            {
                if (p.Qty <= 0 || p.Qty.Equals(""))
                {
                    TempData["ErrorMsg"] = "Quantity cannot be less than zero or empty";
                    Product pro = new ProductServ.ProductServiceClient().GetProductByID(p.myProduct.ID);
                    double avgRating = new ProductServ.ProductServiceClient().getAverageRating(p.myProduct.ID);
                    ProductModel pm = new ProductModel();
                    pm.myProduct = pro;
                    pm.averageRating = avgRating;
                    return View("Details", pm);

                }
                Product product = new ProductServ.ProductServiceClient().GetProductByID(p.myProduct.ID);
                int stock = Convert.ToInt32(product.StockAmount);
                string username = Session["username"].ToString();
                Account a = new AccountServ.AccountServiceClient().getAccountByUsername(username);
                int accountID = a.ID;

                Order check = new ProductOrderClient().getOrderIDByAccountIDStatus(accountID, "Ordered");
                if (p.Qty <= stock)
                {
                    if (check == null)
                    {

                        Order newOrder = new Order();
                        //newOrder.ID = new int();
                        newOrder.DateOfPurchase = System.DateTime.Today;
                        newOrder.WarrantyExpiryDate = System.DateTime.Today.AddYears(2);
                        newOrder.Status = "Ordered";
                        newOrder.AccountID = accountID;
                        new ProductOrderServ.ProductOrderClient().addOrder(newOrder);

                        Order details = new ProductOrderServ.ProductOrderClient().getOrderIDByAccountIDStatus(accountID, newOrder.Status);

                        ProductOrder newProductOrder = new ProductOrder();
                        newProductOrder.OrderID = details.ID;
                        newProductOrder.ProductID = p.myProduct.ID;
                        newProductOrder.Quantity = p.Qty;

                        new ProductOrderServ.ProductOrderClient().addProductOrder(newProductOrder);
                        //return RedirectToAction("Details");

                    }
                    else if (check != null)
                    {
                        ProductOrder checkpo = new ProductOrderServ.ProductOrderClient().getProductOrderID(p.myProduct.ID, check.ID);

                        if (checkpo == null)
                        {

                            Order details = new ProductOrderServ.ProductOrderClient().getOrderIDByAccountIDStatus(accountID, "Ordered");

                            ProductOrder newProductOrder = new ProductOrder();
                            newProductOrder.OrderID = details.ID;
                            newProductOrder.ProductID = p.myProduct.ID;
                            newProductOrder.Quantity = p.Qty;

                            new ProductOrderServ.ProductOrderClient().addProductOrder(newProductOrder);
                        }
                        else if (checkpo != null)
                        {
                            ProductOrder newProductOrder = checkpo;
                            //newProductOrder.Quantity = checkpo.Quantity + p.Qty;
                            int newQty = Convert.ToInt32(checkpo.Quantity) + p.Qty;

                            // new ProductOrderServ.ProductOrderClient().UpdateProductOrder(newProductOrder);
                            new ProductOrderServ.ProductOrderClient().UpdateQtyProduct(newQty, checkpo.ProductID, checkpo.OrderID);
                        }

                    }



                }
                else if (p.Qty > stock)
                {
                    @TempData["OutOfStock"] = "The selected Item is out of stock, try again later";
                    //return RedirectToAction("ProductList");
                    Product pro = new ProductServ.ProductServiceClient().GetProductByID(p.myProduct.ID);
                    double avgRating = new ProductServ.ProductServiceClient().getAverageRating(p.myProduct.ID);
                    ProductModel m = new ProductModel();
                    m.myProduct = pro;
                    m.averageRating = avgRating;
                    return View("Details", m);
                }
                return RedirectToAction("ProductList");
            }
            catch(Exception ex)
            {
                TempData["Error"] = "An error has occurred. Please try again later";
                Product pro = new ProductServ.ProductServiceClient().GetProductByID(p.myProduct.ID);
                double avgRating = new ProductServ.ProductServiceClient().getAverageRating(p.myProduct.ID);
                ProductModel m = new ProductModel();
                m.myProduct = pro;
                m.averageRating = avgRating;
                return View("Details", m);
            }
         }
    }
}

Electros/Electros/Controllers/RegistrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Electros.Models;
using Common;

namespace Electros.Controllers
{
    public class RegistrationController : Controller
    {
        //
        // GET: /Registration/

        public ActionResult Index()
        {
            return View();
        }
        //[Authorize(Roles = "Admin, Auditor")]
        public ActionResult RegisterUser()
        {
            return View(new Models.RegistrationModel());
        }
        public enum RegistrationResult { Successful, usernameExists, EmailExists }

        [HttpPost]
        public ActionResult RegisterUser(RegistrationModel rm)
        {
            
            //continuation of code

            int roleID = 0;
            if (rm.Password.Length < 6)
            {
                TempData["Message"] = "Password needs to be longer";
                //ViewBag.Msg = "Password needs to be longer";
                //return Content("PAssword longer");
                return RedirectToAction("RegisterUser");
            }
            else
            {
                Account checkAccount = new AccountServ.AccountServiceClient().getAccountByUsername(rm.Username);
                User checkEmail = new UserServ.UserServiceClient().getUserByEmail(rm.Email);
                int pin = Convert.ToInt32(rm.PIN);
                Account checkPin = new AccountServ.AccountServiceClient().getAccountByPin(pin);

                if (checkAccount == null && checkEmail == null && checkPin == null)
                {

                    
                        
                        Account a = new AccountServ.AccountServiceClient().getAccountByUsername(rm.Username);

                        string passpin = rm.Password + rm.PIN;
                        string token = new AccountServ.AccountServiceClient().Encrypt(passpin);
                        TempData["Token"] = token;

                        List<int> add = new List<int>();
                        for (int i = 0; i < rm.roles.Count; i++)
                        {
                            if (rm.roles[i].Checked)
                            {
                                roleID = rm.myRole[i].ID;
                                add.Add(roleID);
                            }
                        }
                        int[] arraylist = add.ToArray();
                    //rm.myUser.Email = rm.myUser
                        //USer
                        rm.myUser.Name = rm.Name;
                        rm.myUser.Surname = rm.Surname;
                        rm.myUser.Email = rm.Email;
                        rm.myUser.ResidanceName = rm.ResidanceName;
                        rm.myUser.StreetName = rm.StreetName;
                        rm.myUser.Mobile = rm.Mobile;
                        //Account
                        //rm.myAccount.Username = rm.Username;
                        //rm.myAccount.Password = rm.Password;
                        //// rm.myAccount.PIN = Convert.ToInt32(rm.PIN);
                        //rm.myAccount.PIN = Convert.ToInt32(rm.PIN);
                        Account acc = new Account();
                        acc.Username = rm.Username;
                        acc.Password = rm.Password;
                        acc.PIN = rm.PIN;
                        //new UserServ.UserServiceClient().Create(rm.myUser, arraylist, rm.myAccount);
                        new UserServ.UserServiceClient().Create(rm.myUser, arraylist, acc);
                    
                    
                }
                else
                {
                    if (checkAccount != null)
                    {
                        TempData["Message"] = "Username already exists";
                    }
                    else if(checkEmail != null)
                    {
                        TempData["Email"] = "Email already exists";
                    }
                    else if(checkPin != null)
                    {
                        TempData["PIN"] = "PIN already exists";
                    }
                    
                }
            }

            //return View("RegisterUser");
            return RedirectToAction("RegisterUser");
                
        }
    }
}

Electros/Electros/Controllers/UserAuthenticationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Electros.Models;
using Electros.AccountServ;
using System.Web.Security;
using Common;

namespace Electros.Controllers
{
    public class UserAuthenticationController : Controller
    {
        //
        // GET: /UserAuthentication/

        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(LoginModel data)
        {
            //try
            //{
                if (new AccountServiceClient().isAuthenticatedValid(data.username, data.pin))
                {
                    Account checktoken = new AccountServiceClient().getAccountByUsername(data.username);

                    string passpin = checktoken.Password + checktoken.PIN.ToString();
                    string token = new AccountServiceClient().Encrypt(passpin);
                    string decryptedToken = new AccountServiceClient().Decrypty(data.token);
                    //string checkValue = data
                    // if (token.Equals(data.token))
                    if (decryptedToken.Equals(passpin))
                    {
                        //check with if statement if token is the same with encryption
                        FormsAuthentication.RedirectFromLoginPage(data.username, true);
                        Session["username"] = data.username;
                        Session["accountid"] = checktoken.ID;
                        return RedirectToAction("Index", "Home");
                    }
                    else
                    {
                        ViewBag.Error = "Invalid Login credentials";
                        return View();
                    }

                }
                else
                {
                    ViewBag.Error = "Invalid Login credentials";
                    return View();
                }
            //}
            //catch (Exception ex)
            //{
            //    ViewBag.Error = "Invalid Login credentials";
            //}
            return View();
        }
        //for user to logoff
        public ActionResult LogOff()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");

        }

    }
}

Electros/Electros/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
     <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Styles/default.css")" rel="stylesheet" type="text/css" />
    <link  href="@Url.Content("~/Content/Styles/font.css")" rel="stylesheet" type="text/css"  />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")" type="text/javascript"></script>

</head>
<body>
    
<div id="wrapper">
	<div id="header-wrapper">
		<div id="header" class="container">
			<div id="logo">
				<h1><a href="#">Electros</a></h1>
				<p style="colour:white;">Shop & Report</p>
			</div>
			<div id="social">
				<ul class="contact">
                        @Html.Partial("_LogOnPartial")
                   @*<a href="#">Login</a>*@
					
                     <li> @Html.ActionLink("Basket", "Index", "Basket");</li>
				</ul>
			</div>
		</div>
        
		<div id="menu" class="container">
			@*<ul>*@
                @*<li> @Html.ActionLink("Home", "Index", "Home");</li>
                <li> @Html.ActionLink("Products", "ProductList", "Product");</li>
                <li> @Html.ActionLink("History", "UserHistory", "Basket");</li>
                <li> @Html.ActionLink("Manage Faults", "Index", "Warranty");</li>
                <li> @Html.ActionLink("Admin Faults", "Index", "Admin");</li>
               <li> @Html.ActionLink("Register", "RegisterUser", "Registration");</li>*@
			@*</ul>*@
            @if (Context.User.IsInRole("User") && Context.User.IsInRole("Admin"))
                {
                <ul>
                    
                    <li> @Html.ActionLink("Home", "Index", "Home");</li>
                    <li> @Html.ActionLink("Products", "ProductList", "Product");</li>
                    <li> @Html.ActionLink("History", "UserHistory", "Basket");</li>
                    <li> @Html.ActionLink("Manage Faults", "Index", "Warranty");</li>
                    <li> @Html.ActionLink("Admin Faults", "Index", "Admin");</li>
                   @*<li> @Html.ActionLink("Register", "RegisterUser", "Registration");</li>*@
                   <li> @Html.ActionLink("Statistical Reports", "Index", "StatisticalReport");</li>

               </ul>
                }
                else if (Context.User.IsInRole("Admin"))
                {
                   
                       <li> @Html.ActionLink("Home", "Index", "Home");</li>
                    <li> @Html.ActionLink("Products", "ProductList", "Product");</li>
                    <li> @Html.ActionLink("History", "UserHistory", "Basket");</li>
                    <li> @Html.ActionLink("Manage Faults", "Index", "Warranty");</li>
                    <li> @Html.ActionLink("Admin Faults", "Index", "Admin");</li>
                   @*<li> @Html.ActionLink("Register", "RegisterUser", "Registration"); </li>*@
                <li> @Html.ActionLink("Statistical Reports", "Index", "StatisticalReport");</li>
                
                }
            else if (Context.User.IsInRole("User"))
            {
                 
                       <li> @Html.ActionLink("Home", "Index", "Home");</li>
                    <li> @Html.ActionLink("Products", "ProductList", "Product");</li>
                    <li> @Html.ActionLink("History", "UserHistory", "Basket");</li>
                    <li> @Html.ActionLink("Manage Faults", "Index", "Warranty");</li>
                    
                   <li> @Html.ActionLink("Register", "RegisterUser", "Registration");  </li>
            }
            else
            {
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
            }
		</div>
	</div>
	<div id="page" class="container">
    <div id="header2">
            <script LANGUAGE="JavaScript">
                var now = new Date();

                var days = new Array('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday');

                var months = new Array('January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December');

                var date = ((now.getDate() < 10) ? "0" : "") + now.getDate();

                function fourdigits(number) {
                    return (number < 1000) ? number + 1900 : number;
                }
                today = days[now.getDay()] + ", " +
         months[now.getMonth()] + " " +
         date + ", " +
         (fourdigits(now.getYear()));

                document.write(today);
            </script>
        @*<asp:Label ID="Label1" runat="server" Text="Welcome"></asp:Label>*@
        </div>
        <br />
		<div id="content">
            <div class="post">
				
               @*<p>Add content</p>*@
               @RenderBody()
            </div>
			
		</div>
		<div id="sidebar1">
          
        </div>
	</div>
	
</div>
<div id="footer">
	<p>Copyright (c) 2013 Sitename.com. All rights reserved. Design by <a href="http://www.freecsstemplates.org/" rel="nofollow">FreeCSSTemplates.org</a>. Photos by <a href="http://fotogrph.com/">Fotogrph</a>.</p>
</div>

</body>
</html>

Electros/Electros/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("Log Off", "LogOff", "UserAuthentication") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "Login", "UserAuthentication") ]
}